### ISSUE TITLE
Mensagem "errada" para inserir o produto no momento de cadastrar o pedido

### ISSUE THREAD

**Issue by VitorLack** [Monerat/SerraTec-POO-Grupo3#7]
Quando vamos cadastrar um pedido, inserimos a data, o id do cliente e quando deveria pedir pra inserir um produto no pedido, apresenta a mensgaem "Deseja adicionar mais 1 produto ao pedido?" quando deveria ser "Insira o produto".

**Comment by Monerat** [comment]
Não é um problema, é uma feature.
